services:
    postgres:
        image: postgres:latest
        container_name: postgres
        environment:
            POSTGRES_USER: keycloak
            POSTGRES_PASSWORD: password
            POSTGRES_DB: keycloak

        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - keycloak-network
        ports:
            - 5432:5432

    keycloak:
        image: quay.io/keycloak/keycloak:24.0.2
        container_nme: keycloak
        depends_on:
            - postgres
        environment:
            KEYCLOAK_ADMIN: admin
            KEYCLOAK_PASSWORD: admin
            KC_DB: postgres
            KC_DB_URL: jdbc:postgres://postgres:5432/keycloak
            KC_DB_USERNAME: keycloak
            KC_DB_PASSWORD: password
            KC_HOSTNAME: localhost

        networks:
            - keycloak-network
        ports:
            - 8080:8080
        command: start-dev


volumes:
    postgres_data:

networks:
    keycloak-network:
        driver:bridge